"""add bar_code to user table

Revision ID: 39d6974cfa02
Revises: ae38d23012cf
Create Date: 2024-04-13 02:27:00.134256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d6974cfa02'
down_revision: Union[str, None] = 'ae38d23012cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bar_code', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['bar_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'bar_code')
    # ### end Alembic commands ###
