"""add status col to UserDocs

Revision ID: 52ff64425730
Revises: 92b9d35775e6
Create Date: 2024-04-16 20:51:39.932571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ff64425730'
down_revision: Union[str, None] = '92b9d35775e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE documentstatus AS ENUM ('NULL', 'ERROR', 'PENDING', 'SUCCESS')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('needer_files', sa.Column('status', sa.Enum('ERROR', 'PENDING', 'SUCCESS', 'NULL', name='documentstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('needer_files', 'status')
    # ### end Alembic commands ###
