"""fix order table

Revision ID: 6d17fe60ab76
Revises: 73f92c411e6b
Create Date: 2024-03-26 00:58:49.184143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d17fe60ab76'
down_revision: Union[str, None] = '73f92c411e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('contact_name', sa.String(length=50), nullable=False))
    op.drop_column('orders', 'last_name')
    op.drop_column('orders', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('orders', 'contact_name')
    # ### end Alembic commands ###
