"""add column to item table

Revision ID: 73f92c411e6b
Revises: cada9825d461
Create Date: 2024-03-26 00:46:34.555154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f92c411e6b'
down_revision: Union[str, None] = 'cada9825d461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_publish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_publish')
    # ### end Alembic commands ###
