"""add created_at attr to Order

Revision ID: fa39c795b4c3
Revises: d569fd5f263e
Create Date: 2024-05-03 19:48:29.837917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa39c795b4c3'
down_revision: Union[str, None] = 'd569fd5f263e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'created_at_time')
    # ### end Alembic commands ###
